version: 2

sources:
  - name: "{{env_var('HEVO_PREFIX'}}"
    database: "{{ env_var('SNOW_DB') }}"
    schema: "{{ env_var('SNOW_SCHEMA') }}"
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
