version: 2

sources:
  - name: hevo_source
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: "{{ env_var('DBT_SOURCE_SCHEMA') }}"
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
