version: 2

models:
  - name: customers
    description: "Final transformed table providing a 360-degree view of customer activity."
    columns:
      - name: customer_id
        description: "The primary key for this model"
        tests:
          - unique
          - not_null

      - name: number_of_orders
        description: "Total count of orders placed by the customer"
        tests:
          - not_null
