version: 2

sources:
  - name: hevo_raw
    database: "{{ env_var('SNOW_DB') }}"
    schema: "{{ env_var('SNOW_SCHEMA') }}"
    tables:
      - name: raw_customers
        
      - name: raw_orders
        
      - name: raw_payments


